### PR TITLE
Lots of Improvements

### PR DESCRIPTION
**Pull request by bhubbard**
Here are the main changes I made.

= 1.1.5 =
* Added basic schema support to Single Listings Template
* Added support for Jetpack publicize and markdown editors
* Added Jetpack shortcode links in messages about shortcodes when editing a property
* Added DNS Prefetch Support for scripts used on Single Listings Template

= 1.1.4 =
* Minified CSS, Setup SCSS for better site performance
* Updates to script calls to improve site performance
* Updated jQuery Validate to 1.13.1

### CODE REVIEW

**Comment by bhubbard** [comment]
@davebonds - I know this has a huge list of changes, was just wondering if you got to start taking a look at it?

**Comment by davebonds** [comment]
Not yet. Been tied up with another project so WP Listings has taken a back seat for now. Will review soon.

**Comment by bhubbard** [comment]
@davebonds - Was wondering if you got to looks this over yet, I know your busy, but I have other issues/features I would like to submit to this project.

**Comment by davebonds** [comment]
For sure.. thanks for all your help on this. Just got back to this project and reviewing your pull requests and other open issues now. This project is my main focus for the next little while. Will update you as soon as I give it a good look over.

In the meantime though, have you noticed this issue? I can't seem to replicate it: https://wordpress.org/support/topic/wp-listings-search-not-working?replies=12

**Comment by bhubbard** [comment]
I haven't noticed, but I will see if I can replicate the issue.

**Pull request merged**
